### ISSUE TITLE
master branch is failing

### ISSUE THREAD

**Issue by gboeing** [conda-forge/demquery-feedstock#2]
@ocefpaf @kylebarron it looks like the master branch of this feedstock is failing.

**Comment by kylebarron** [comment]
No idea why. The PyPI package hasn't changed since the bot's PR was made.

**Comment by gboeing** [comment]
My guess is #1 was really old and needed to be rerendered. I had just added the `bot-rerun` label but it looks like it was merged before the rerun occurred.

**Comment by kylebarron** [comment]
Ok, I'll push an 0.3.1 to PyPI to see if it creates a new PR here

**Comment by gboeing** [comment]
You can also just open a new PR here manually, with a rerendered feedstock

**Comment by ocefpaf** [comment]
Let's try this first:

@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
The bot seems to be down :-/

I'll send a rerender PR tomorrow if no one beats me to it.

**Comment by kylebarron** [comment]
I pushed 0.3.1 to PyPI and merged here, seems to be fixed.
